apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ebcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ebcq
    app.kubernetes.io/part-of: test-app-wdcs
  name: test-component-ebcq
  namespace: build-templates-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-ebcq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-ebcq
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:1b71f608cb964a23b6d46b8a55a58a67
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
